### ISSUE TITLE
Higher python version support?

### ISSUE THREAD

**Issue by Madoshakalaka** [kootenpv/sysdm#1]
Sysdm is exactly what I want! Amazing work!

However I spent hours trying to validate that it indeed works. The major deterent being I'm a python 3.6/3.7 user and the readme badges topped at 3.5.

I forked sysdm, installed it under python 3.7 and roughly skimmed, test-ran the code. So far no problem occured. 

Higher python versions should be backwards compatible, what's the reason to not include those badges? I guess there should be some unit testing maybe with `tox`, but the code looks free of compatibility issues.

**Comment by kootenpv** [comment]
It's honestly just copying badges from an older project. I'll update to reflect the badges. You're right about the testing, though it always feels a bit awkward with a lot of bash commands / UI related code in there.

**Comment by kootenpv** [comment]
I have updated the badges! Thanks, and I am glad you like it. Let me know if there are things you are missing or if you have further ideas for improvement :)

**Comment by Madoshakalaka** [comment]
Thanks! I just had a pull request and I believe I somewhat re-enabled python 2.7 support though. Could you add python 2.7 back if you like my pull request.
